# Deconvolution of transcriptomes and methylomes

We describe our methods in this chapter.  The pre-eliminary pipeline and simple results are described in the manuscript submitted to  Springer-Verlag’s Lecture Notes in Computer Science ([LNCS](http://www.springer.com/gb/computer-science/lncs)) entitled **Application of Independent Component Analysis to Tumor Transcriptomes Reveals Specific And Reproducible Immune-related Signals** that is placed at the end of this chapter. In the final thesis final pipeline will be split into following structure

## From blind deconvolution to cell-type quantification: general overview

Few lines describing our idea

Figure?

### The ICA-based deconvolution of Transcriptomes

* remind shortly ICA
* describe stabilisation procedure *icasso*
* explain IC-metagene concept

If completed add related section about two other ways of getting metagenes

 * attractor metagenes
 * k-lines

### Interpretation of Independent components

#### Correlation based identification of confounding factors 

#### Identification of immune cell types with enrichment test / other

### Transforming metagenes into signature matrix

### Regression-based estimation of cell-type proportions : solving system of equations

## *DeconICA* R package for ICA-based deconvolution 

This part of the chapter will be adapted from package vignettes

It will contain 

* technical package description

* user guide 

* examples

  ​

\includepdf[pages={1-}, scale=1]{pdf-ext/LVAICA.pdf}







