# Conclusions  and perspectives {#conclusions}

Here we will have some interesting and well-written conclusion that will validate the quality of this thesis. 

A major part of this thesis has been to reproduce earlier work[7][8], and it has been time consuming to try to reproduce different approaches or scripts. It has been brought up that other scientists have struggled - and many failed - to reproduce another scientists work[48]. The article states that of 1,576 researchers, over 70% have failed to reproduce others work and over 50% have failed to reproduce their own. 52% of the participants in the survey state that is is a "significant crisis", which indicates that we could call this a "reproducibility crisis"[48]. Such high numbers may suggest in- accurate or poor documentation of the different steps towards achieving the results, or even going as far as suggesting untrustworthy results. The latter is a bold statement, but according to the article, less than 31% believe that struggles to reproduce published results are due to wrong results[48]. 