# (PART) Discussion {-}

# Discussion {#discussion}

# Conclusions  and perspectives {#conclusions}

Here we will have some interesting and well-written conclusion that will validate the quality of this thesis. 

Problems:

* reproducibility of other tools (code accessing, making work, pre-processing)

* no-spatial dimension

* heterogeneity - analyse sample by samples (need of big dimension)

* time dimention

* validation - no gold statndard

* our solution - more contex specific but less interpretable?

  

A major part of this thesis has been to reproduce earlier work[7][8], and it has been time consuming to try to reproduce different approaches or scripts. It has been brought up that other scientists have struggled - and many failed - to reproduce another scientists work[48]. The article states that of 1,576 researchers, over 70% have failed to reproduce others work and over 50% have failed to reproduce their own. 52% of the participants in the survey state that is is a "significant crisis", which indicates that we could call this a "reproducibility crisis"[48]. Such high numbers may suggest in- accurate or poor documentation of the different steps towards achieving the results, or even going as far as suggesting untrustworthy results. The latter is a bold statement, but according to the article, less than 31% believe that struggles to reproduce published results are due to wrong results[48]. 



Moreover, the immune cells can be situated in different locations, either in the core, in the invasive margin or in the adjacent tertiary lymphoid structures (TLS), ectopic lymphoid formations found in inflamed, infected, or tumoral tissues exhibiting all the characteristics of structures in the lymph nodes (LN) associated with the generation of an adaptive immune response (Dieu-Nosjean et al. 2014): a correlation has been found between high densities of TLS and prolonged patient’s survival in more than 10 different types of cancer (Sautès-Fridman et al. 2016).

For instance, CD8+ T cells can be visible in both the invasive margin and the core of the tumor, while the TLS seem to lack these cells. In addition, the mixture of immune cells can vary differently in relation to tumor types. Some components of the immune contexture, more than others, are helpful in terms of good prognosis: this fact is shared by multiple papers, such as Dave et al. 2004, which paved the way in the early years of the XXI century, while in Parker et al. 2008 and Parker et al. 2009



—-

. In the case of T cells and cancer, although the total frequencies of tumor-specific T cells are difficult to assess (due to uncertainties about the range of targets, see below), reports of blood-derived tumor-specific T cells suggest that these frequencies are low (much less than 1% of CD8þ T cells, which typically make up 10%–20% of peripheral blood mononuclear cells; refs. 50, 51). Therefore, at least in the case of blood, a large part of the signal measured in bulk T-cell profiles should originate from irrelevant cells. In tumor tissues, the problem is certainly less severe, in that tumor-infiltrating T cells are likely enriched for tumor-specific T cells. However, as discussed above, because the immunologic composition of tumor tissues is complex and heterogeneous, similar efforts dedicated to identifying, quantifying, and profiling relevant (tumor-specific) T cells are still needed.